config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :todo_lists  do
    resources :todo_items do
      member do
        patch :complete
      end
    end
  end
  root 'todo_lists#index'

end

app/models/todo_item.rb
class TodoItem < ActiveRecord::Base
  belongs_to :todo_list

  def completed?
    !completed_at.blank?
  end

  def last?
    # byebug
    todo_list.todo_items.last==self
  end
end

app/models/todo_list.rb
class TodoList < ActiveRecord::Base
  has_many :todo_items
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :todo_lists
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController
  before_action :set_todo_list
  before_action :set_todo_item, except: [:create]
  before_action :authenticate_user!
  respond_to :html, :js

  def create
    @todo_item = TodoItem.new
    @todo_item.content = params[:todo_item][:content]
    @todo_item.todo_list_id = params[:todo_list_id]
    @todo_item.save!
    if @todo_item.errors.empty?
      flash[:success] = 'Todo List item was created.'
    else
      flash[:error] = 'Todo List item could not be created.'
    end

    # byebug
    @todo_list = TodoList.find(@todo_item.todo_list_id)
    respond_with @todo_item do |format|
      format.js { render 'todo_lists/update', :todo_list => @todo_list}
    end
  end

  def destroy
    @todo_list = TodoList.find(@todo_item.todo_list_id)
    if @todo_item.destroy
      flash[:success] = 'Todo List item was deleted.'
    else
      flash[:error] = 'Todo List item could not be deleted.'
    end
    respond_with @todo_list do |format|
      format.js { render 'todo_lists/update', :todo_list => @todo_list}
    end
  end

  def complete
    @todo_item.update_attribute(:completed_at, Time.now)
    redirect_to root_url, notice: 'Todo item completed'
  end

  private

  def set_todo_list
    @todo_list = TodoList.find(params[:todo_list_id])
  end

  def set_todo_item
    @todo_item = @todo_list.todo_items.find(params[:id])
  end

  def todo_item_params
    params[:todo_item].permit(:content)
  end

  def render_todo_list_items(id)
    # @project = Project.find(id)
    # respond_to do |format|
    #   format.js { render 'projects/update' }
    # end
  end
end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  before_action :set_todo_list, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /todo_lists
  # GET /todo_lists.json
  def index
    @todo_lists = current_user.todo_lists
    # TodoList.all
  end

  # GET /todo_lists/1
  # GET /todo_lists/1.json
  def show
    redirect_to root_url
 end

  # GET /todo_lists/new
  def new
    @todo_list = TodoList.new
  end

  # GET /todo_lists/1/edit
  def edit
    redirect_to root_url
  end

  # POST /todo_lists
  # POST /todo_lists.json
  def create
    @todo_list = TodoList.create(title: "New Project", user_id:  current_user.id)
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'Todo list was successfully created.' }
      # format.js { render 'todo_lists/update', :todo_list => @todo_list}
    end
  end

  # PATCH/PUT /todo_lists/1
  # PATCH/PUT /todo_lists/1.json
  def update
    respond_to do |format|
      if @todo_list.update(todo_list_params)
        format.html { redirect_to root_url, notice: 'Todo list was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo_list }
      else
        format.html { render :edit }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todo_lists/1
  # DELETE /todo_lists/1.json
  def destroy
    @todo_list.destroy
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'Todo list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo_list
      @todo_list = TodoList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_list_params
      params.require(:todo_list).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Lato:300,400,700' rel='stylesheet' type='text/css'>
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
</head>
<body>

<div id="header">
  <ul>
    <div class="to_left">
      <li>
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
      </li>
    </div>
    <div class="to_right">
      <% if user_signed_in? %>
        <li><%= link_to 'Account', edit_user_registration_path %></li>
        <li> <%= link_to "Sign out", destroy_user_session_path, method: :delete %> </li>
      <% else %>
        <li> <%= link_to "Register", new_user_registration_path %> </li>
        <li> <%= link_to "Sign in", new_user_session_path %> </li>
      <% end %>
    </div>
  </ul>
</div>



<div id="main_page">
  <%= yield %>
</div>

  <div id="footer">
    <p>&copyRubyGarage</p>
  </div>

</body>
</html>

app/views/todo_items/_form.html.erb
<% # byebug %>
<%= form_for([todo_list, todo_list.todo_items.build], remote: true) do |f|%>
  <%= button_tag  do %>
    <i class='fa fa-plus fa-2x'></i>
  <% end %> 
  <%= f.text_field :content, placeholder: 'Start typing here to create a task...'%>
  <%= f.submit 'Add Task' %>
<% end %>

app/views/todo_items/_todo_item.html.erb
<% #byebug %>
 <% #todo_items.each do |todo_item| %>
  <% unless todo_item.id.nil? %>
    <div class="row clearfix <%=' radius-bottom' if todo_item.last? %>" >
      <% if todo_item.completed? %>
        <div class="complete">
          <%= link_to complete_todo_list_todo_item_path(todo_item.todo_list_id, todo_item.id), method: :patch do %>
            <i class='fa fa-check-square-o'></i>
          <% end %>
        </div>
        <div class="todo_item">
          <p style="opacity: 0.4;"><strike><%= todo_item.content %></strike></p>
        </div>
        <div class="action_buttons">
          <%= link_to '' do %>
            <i class='fa fa-sort'></i>
          <% end %> | 
          <%= link_to '', class: 'todo_item_edit' do %>
            <i class='fa fa-pencil'></i>
          <% end %> | 
          <%= link_to todo_list_todo_item_path(todo_item.todo_list_id, todo_item.id), method: :delete, data: { confirm: 'Are you sure?'}, remote: true do %>
            <i class='fa fa-trash'></i>
          <% end %>
        </div>
      <% else %>
        <div class="complete">
          <%= link_to complete_todo_list_todo_item_path(todo_item.todo_list_id, todo_item.id), method: :patch do%>
            <i class='fa fa-square-o'></i>
          <% end %>
        </div>
        <div class="todo_item">
          <p><%= todo_item.content %></p>
        </div>
        <div class="action_buttons">
          <%= link_to '' do %>
            <i class='fa fa-sort'></i>
          <% end %> | 
          <%= link_to '' do %>
            <i class='fa fa-pencil'></i>
          <% end %> | 
          <%= link_to todo_list_todo_item_path(todo_item.todo_list_id, todo_item.id), method: :delete, data: { confirm: 'Are you sure?'}, remote: true do %>
            <i class='fa fa-trash'></i>
          <% end %>
        </div>
      <% end %>
    </div>
  <% end %>
<% #end %>

app/views/todo_lists/_form.html.erb
<%= form_for(todo_list) do |f| %>
  <%= f.label "#{todo_list.title}" %>
  <%= f.text_field :title %>
  <% f.submit %>
<% end %>

app/views/todo_lists/edit.html.erb
<% byebug %>
<h1 class="todo_list_title">Edit Todo List</h1>

<div class="forms">
  <%= render 'form' %>
</div>

<div class="links">
  <%= link_to 'Cancel', todo_lists_path %>
</div>

app/views/todo_lists/index.html.erb
<h1>SIMPLE TODO LISTS</h1>
<h2>FROM RUBY GARAGE</h2>

<% @todo_lists.each do |todo_list| %>
  <% # byebug %>
  <div class="container" >
    <div class="row clearfix todo_list_title">
      <div class="list_icon">
        <i class='fa fa-calendar'></i>
      </div>
      <div class="td_title" id=<%= 'todo_list_' + todo_list.id.to_s %> >
        <%= form_for(todo_list) do |f| %>
          <%= f.label "#{todo_list.title}" %>
          <%= f.text_field :title, class: 'input_title' %>
        <% end %>
      </div>
      <div class="action_buttons">
        <%= link_to '', class: 'todo_list_edit' do %>
          <i class='fa fa-pencil'></i>
        <% end %> | 
        <%= link_to todo_list_path(todo_list), method: :delete, data: { confirm: 'Are you sure?'} do %>
          <i class='fa fa-trash'></i>
        <% end %>
      </div>
    </div>  
    <div class="todo_items_wrapper radius-bottom" id=<%= 'todo_list_' + todo_list.id.to_s + '_items' %>>
      <div id="form" class=<%= 'radius-bottom' if todo_list.todo_items.empty? %>>
        <%= render 'todo_items/form', :todo_list => todo_list%>
      </div>
      <% todo_list.todo_items(1) %>
      <div class="items_list">
        <%= render todo_list.todo_items%>
      </div>
    </div>  
  </div>

<% end %>

<div >
<%= button_to "Add TODO List", todo_lists_path, method: :create, remote: true, id: 'add_list' %>
    <!-- <i class='fa fa-plus fa-2x' id='fa_plus'></i> -->
</div>

app/views/todo_lists/new.html.erb
<h1 class="todo_list_title">New Todo List</h1>

<div class="forms">
  <%= render 'form' %>
</div>

<div class="links">
  <%= link_to 'Back', todo_lists_path %>
</div>

app/views/todo_lists/new.js.erb
$("<%= '#todo_list_' + @todo_list.id.to_s + '_items'%>").children('.items_list').html("<%= j render partial: @todo_list.todo_items %>" );

app/views/todo_lists/show.html.erb
<p id="notice"><%= notice %></p>

<h2 class="todo_list_title"><%= @todo_list.title %></h2>
<p class="todo_list_sub_title"><%= @todo_list.description %></p>

<div id='todo_items_wrapper'>
  <%= render @todo_list.todo_items %>
  <div id="form">
    <%= render 'todo_items/form'%>
  </div>
</div> 

<div class="links">
  <%= link_to 'Edit', edit_todo_list_path(@todo_list) %> |
  <%= link_to 'Delete', todo_list_path(@todo_list), method: :delete, data: {confirm: 'Are you sure?'} %> |
  <%= link_to 'Back', todo_lists_path %>
</div>

app/views/todo_lists/update.js.erb
<% #byebug %>
$("<%= '#todo_list_' + @todo_list.id.to_s + '_items'%>").children('.items_list').html("<%= j render partial: @todo_list.todo_items %>" );
<% unless flash[:error] == nil %>
  $(".alert").html("<%= flash[:error] %>" );
  setTimeout('$(".alert").html("")', 3000)
<% end %>
<% unless flash[:success] == nil %>
  $(".notice").html("<%= flash[:success] %>" );
  setTimeout('$(".notice").html("")', 3000)
<% end %>